### PR TITLE
Fix PR Page (fixes #56)

### LINKED ISSUE #56: Jira ticket numbers in PR titles are no longer converted into links
GitHub has done some work updating PR page and I guess CSS selectors are no longer valid and jira ticket links aren't inserted anymore.

It seems that GitHub may be rolling out this change gradually so not everyone is affected yet.

### PR DESCRIPTION
**Pull request by MaximBelov**
This PR fixes #56

### CODE REVIEW

File: src/content.js [hunk 1]
```diff
@@ -279,9 +278,9 @@ function handleCommitsTitle() {
 }
 
 async function handlePrPage() {
-    const titleEl = document.querySelector('h1 > .js-issue-title');
+    const titleEl = document.querySelector('h1 > span');
```
Comment (RobQuistNL) [inline src/content.js]:
```suggestion
    const titleEl = document.querySelector('h1 > span.markdown-title');
```

just to make it a little more specific - there are multiple span elements in that h1 selector.

**Review by RobQuistNL — COMMENTED** [review]
Thank you so much for the fix! This does indeed fix the issues and it's working for me again, too. 

I have some questions and remarks - if you're okay with it I'm also willing to append those changes to your PR and merge it so we can release 1.3.1.

Thank you again! 🙏

File: src/content.js (hunk 1 above)
Comment (MaximBelov) [reply src/content.js]: done

File: src/content.js [hunk 2]
```diff
@@ -85,7 +85,6 @@ function userHTMLContent(text, user) {
 function buildLoadingElement(issueKey) {
     const el = document.createElement('div');
     el.id = 'insertedJiraData';
-    el.className = 'gh-header-meta';
```
[the remark this answers is not in the document]
Comment (MaximBelov) [reply src/content.js]: done

**Review by RobQuistNL — APPROVED** [review]
LGTM!

Thanks a ton for your contribution 🙏
